
db.createCollection( 'ms_objects', {validator: {$jsonSchema: {bsonType: 'object',description:'the general manuscript object, usually has a shelfmark, is a codex (or part of one)',title:'ms_objects',required: [         'id',          'ark',          'ms_type',          'shelfmark',          'extent',          'dim',          'form',          'parts',          'has_bind',          'location',          'refs'],properties: {id: {bsonType: 'objectId'},ark: {bsonType: 'string'},ms_type: {enum: },shelfmark: {bsonType: 'string'},summary: {bsonType: 'string'},extent: {bsonType: 'string'},weight: {bsonType: 'string'},dim: {bsonType: 'object',
title:'object',properties: {type: {enum: },value: {bsonType: 'string'}}},form: {enum: },fol: {bsonType: 'string'},fol_note: {bsonType: 'array',items: {bsonType: 'string'}},features: {enum: },parts: {bsonType: 'array',items: {
title:'object',required: [         'part_id',          'sequence'],properties: {part_id: {bsonType: 'objectId'},sequence: {bsonType: 'int'}}}},paratext: {bsonType: 'array',items: {
title:'object',required: [         'id',          'para_type',          'locus',          'lang',          'hand'],properties: {id: {bsonType: 'objectId'},para_type: {enum: },locus: {bsonType: 'string'},event: {enum: },lang: {bsonType: 'array',items: {bsonType: 'objectId'}},label: {bsonType: 'string'},work: {bsonType: 'array',items: {
title:'object',required: [         'work_id'],properties: {work_id: {bsonType: 'objectId'},as_written: {bsonType: 'string'},note: {bsonType: 'string'}}}},note: {bsonType: 'string'},transcription: {bsonType: 'string'},translation: {bsonType: 'string'},assoc_person: {bsonType: 'array',items: {
title:'object',required: [         'person_id',          'role'],properties: {person_id: {bsonType: 'objectId'},as_written: {bsonType: 'string'},role: {enum: },note: {bsonType: 'string'}}}},assoc_place: {bsonType: 'array',items: {
title:'object',required: [         'place_id',          'event'],properties: {place_id: {bsonType: 'objectId'},as_written: {bsonType: 'string'},event: {enum: },note: {bsonType: 'string'}}}},assoc_date: {bsonType: 'array',items: {
title:'object',required: [         'date_type',          'date'],properties: {date_type: {enum: },date: {bsonType: 'date'},as_written: {bsonType: 'string'},note: {bsonType: 'string'}}}},hand: {bsonType: 'object',
title:'object',required: [         'writing system',          'script'],properties: {writing system: {bsonType: 'objectId'},script: {bsonType: 'objectId'},script_note: {bsonType: 'string'},hand_note: {bsonType: 'string'}}},features: {enum: },refs: {bsonType: 'array',items: {
title:'object',required: [         'ref_id'],properties: {ref_id: {bsonType: 'objectId'},ref_pg: {bsonType: 'string'},ref_note: {bsonType: 'string'}}}}}}},ornamentation: {bsonType: 'array',items: {
title:'object',required: [         'features'],properties: {features: {enum: },orn_note: {bsonType: 'array',items: {bsonType: 'string'}}}}},has_bind: {bsonType: 'bool'},bind_note: {bsonType: 'array',items: {bsonType: 'string'}},cond_note: {bsonType: 'array',items: {bsonType: 'string'}},iiif: {bsonType: 'array',items: {
title:'object',required: [         'manifest_type',          'iiif_manifest'],properties: {manifest_type: {enum: },iiif_manifest: {bsonType: 'string'},text_direction: {enum: },behavior: {enum: }}}},location: {bsonType: 'array',items: {
title:'object',required: [         'repository'],properties: {collection: {enum: },repository: {bsonType: 'objectId'},settlement: {bsonType: 'string'}}}},provenance: {bsonType: 'array',items: {bsonType: 'string'}},assoc_date: {bsonType: 'array',items: {
title:'object',required: [         'date_type',          'date_normalized',          'date'],properties: {date_type: {enum: },date_normalized: {bsonType: 'date'},date: {bsonType: 'string'},as_written: {bsonType: 'string'},note: {bsonType: 'string'}}}},viscodex: {bsonType: 'array',items: {
title:'object',required: [         'label',          'url'],properties: {label: {bsonType: 'string'},url: {bsonType: 'string'}}}},refs: {bsonType: 'array',description:'Cataloguing History',items: {
title:'object',required: [         'ref_id'],properties: {ref_id: {bsonType: 'objectId'},ref_pg: {bsonType: 'string'},ref_note: {bsonType: 'string'},shelfmark_alt: {bsonType: 'string'}}}},bib: {bsonType: 'array',items: {
title:'object',required: [         'bib_id'],properties: {bib_id: {bsonType: 'objectId'},bib_pg: {bsonType: 'string'},bib_note: {bsonType: 'string'}}}},cataloguer: {bsonType: 'array',items: {
title:'object',required: [         'cataloguer_id',          'timestamp'],properties: {cataloguer_id: {bsonType: 'objectId'},cataloguer_note: {bsonType: 'string'},timestamp: {bsonType: 'timestamp'}}}}}         }      }});  