
db.createCollection( 'work', {validator: {$jsonSchema: {bsonType: 'object',title:'work',required: [         'pref_title',          'genre'],properties: {pref_title: {bsonType: 'string', description:'Preferred Title: The form of the work\'s title used as the primary label for the work'},orig_lang: {bsonType: 'objectId', description:'Original Language: The language in which the work was originally composed. Must be an objectId of a corresponding language object'},orig_lang_title: {bsonType: 'array',description:'Original Language Title: An expression of the work\'s title given in the language in which the work was originally composed',items: {bsonType: 'string'}},alt_title: {bsonType: 'array',description:'Alternative Title: Variant forms of the work\'s title, including the language code',items: {
title:'object',properties: {lang: {bsonType: 'string', ISO 639-1 or ISO 639-2 language code, description:'Language: The language code representing the language of the corresponding title'},title: {bsonType: 'string'}}}},creation_date: {bsonType: 'object',description:'Creation Date: The time span during which the work was composed; expressed in both human- and machine-readable formats',
title:'object',properties: {label: {bsonType: 'string', description:'Label (Creation Date): A human-readable expression of the timespan during which the work was composed'},normalized: {bsonType: 'date', An ISO 8601 date or date range, description:'Normalized (Creation Date): A machine-readable expression of the timespan during which the work was composed'}}},desc: {bsonType: 'string', description:'Description: A brief, prose summary of the contents, context, or subjects of the work. Use for disambiguation.'},genre: {bsonType: 'array',description:'Genre: The stylistic type or category to which the work belongs. Must be an objectId of an existing Genre object.',items: {bsonType: 'objectId'}},incipit: {bsonType: 'string'},bibl: {bsonType: 'array',description:'Bibliography: A secondary scholarly source that provides information about the work ',items: {
title:'object',properties: {ref: {bsonType: 'objectId', description:'Reference: The objectId of a bibliographic item. Must be an objectId of an existing Bibl object'},type: {enum: ['edition', 'translation', 'other', null], description:'Type (Bibliography): The type of bibliographic item cited, i.e. \'edition\', translation\', or \'other\'.',},cite_rg: {bsonType: 'string', description:'Cited Range: The logic subsection of the bibliographic item being referenced'}}}},rel_con: {bsonType: 'array',description:'Related Concept: An equivalent or close matching concept in an external authority file',items: {
title:'object',properties: {title: {bsonType: 'string', description:'Title (Related Concept): The uniform or prefererd title form for the related concept from an external authority file'},uri: {bsonType: 'string', Must be a URI, description:'URI: The Uniform Resource Identifier for the related concept'},source: {enum: ['VIAF', 'LoC', 'Syriaca', 'HAF', 'Pinakes'], description:'Source (Related Concept): The authority service or database containing the related concept entry',}}}},refno: {bsonType: 'array',description:'Reference Number: Contains the uniform title, entry number, and source for the work in a standard reference list',items: {
title:'object',properties: {title: {bsonType: 'string', description:'Title (Reference Number): The uniform title provided in the standardized reference work entry'},id: {bsonType: 'string', description:'Identifier: The entry number or other standard identifier for the work in a standard reference work'},source: {enum: ['CPG', 'CPL', 'BHO', 'BHG', null], description:'Source (Reference Number): The reference work in which the entity is found ',}}}},assoc_pers: {bsonType: 'array',description:'Associated Person: A person entity connected to the work resource through a given role',items: {
title:'object',properties: {id: {bsonType: 'objectId', description:'Identifier (Associated Person): The objectId of the associated person record. Must be an objectId of an existing Person object '},role: {enum: ['author', 'translator', 'editor', 'subject', null], description:'Role (Associated Person): Describes the kind of association between the person and work',}}}},rel_work: {bsonType: 'array',description:'Related Work: A work entity with an associative or hierarchical link to a given work',items: {
title:'object',properties: {type: {enum: ['isPartOf', null], description:'Type (Related Work): Describes the kind of relation asserted between two work entities.',},id: {bsonType: 'objectId', description:'Identifier (Related Work): The objectId of the related work entity. Must be an objectId of an existing Work object'}}}},version: {bsonType: 'array',items: {
title:'object',properties: {expression: {bsonType: 'string'},language: {bsonType: 'objectId'},title: {bsonType: 'objectId'},incipit: {bsonType: 'string'}}}}}         }      }});  